pipeline:
  identifier: Build_ShobhitSingh11_podio_php_1703146552422
  name: Build podio-php
  orgIdentifier: default
  projectIdentifier: autogen
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: shobhit_connector
        repoName: ShobhitSingh11/podio-php
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      password: <+input>
                      repo: hello/world
                      tags: latest
                      username: <+input>
                  timeout: ""
                  type: Plugin
              - step:
                  identifier: composerinstall
                  name: composer_install
                  spec:
                    command: composer install
                    runAsUser: "1000"
                  timeout: ""
                  type: Run
              - step:
                  identifier: composertestreport
                  name: composer_test_report
                  spec:
                    command: composer test
                    runAsUser: "1000"
                  timeout: ""
                  type: Run
              - step:
                  identifier: composertestcoverage
                  name: composer_test_coverage
                  spec:
                    command: composer coverage
                    runAsUser: "1000"
                  timeout: ""
                  type: Run
              - step:
                  identifier: composerlint
                  name: composer_lint
                  spec:
                    command: composer lint
                    runAsUser: "1000"
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
